# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 023008c74048d722992ae79ddbefc0fd09e8a664142d5d6a8f406f0e41163417f87f9d3f03517590b21bbbc9246025ea86188ac04c6a83f1289887ec657abaa0

test:
  secret_key_base: e6e96369d0dd7fcf062e1740387f2b2dd1e924538428a895b3f4e2530eb4d89c5d67f7f2ef2ceed5264259ce5e098760f2e9625267296f8bd122eff01d6300d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
